### ISSUE TITLE
Implementor: File storage configuration

### ISSUE THREAD

**Issue by scottnath** [punchcard-cms/punchcard#242]
For file/image uploads, the system needs to know _where_ the files are going to be stored and their unique name after they have been stored

``` gherkin
Feature: Files stored as content
  As a Punchcard implementor
  I want to setup file storage
  So that content creators can have files as part of their content

  Scenario: Configure storage
    Given that I need external file storage for file uploads
      And that sometimes I need local storage for file uploads
    When I am setting up my CMS configuration
    Then I should have the ability to add configuration for file storage
      And the configuration for storage should be an object
      And said object should contain key of `type`
      And `type` should be a string
      And the content of `type` shall be determined by the pluggable storage options available.
```

---

**Files stored as Content**
- [ ] configuration

**Comment by scottnath** [comment]
The designation of a storage location is blocked by https://github.com/punchcard-cms/punchcard/issues/243

**Comment by scottnath** [comment]
no longer blocked

**Comment by Snugug** [comment]
We want a pluggable file storage solution that can be used irrelevant of environment. Instead of having a user configure local and production file storage options, have them just configure what they need at the moment they need it (on production, don't need local, and vice-versa).

The plugin system should have a shared interface for saving and retrieving files, with the plugins handling the actual execution (all async). Saving only something like relative path from the plugin's defined root, which should be configurable.

**Comment by Snugug** [comment]
It should also handle errors consistently across all storage plugins.

I don't think we need to make it pluggable via Plugabilly to begin with, but we should consider that we will want to do that at some point in the future

**Comment by scottnath** [comment]
@Snugug I changed this story to be non-storage-options specific config.

I created a plugable storage story: #492

**Comment by Snugug** [comment]
Resolved with https://github.com/punchcard-cms/punchcard/pull/529
