### ISSUE TITLE
Content Creator: Understand content types and take action

### ISSUE THREAD

**Issue by ineedsubstance** [punchcard-cms/punchcard#249]
_As a_ Content Creator, _I want_ to understand which content type I need and have the ability to take action quickly _so that_ I can create and edit content with ease.

``` gherkin
Feature: Content type list context
  As a Content Creator,
  I want to understand which content type I need
    And have the ability to take action quickly
  So that I can create and edit content with ease.

  Scenario: Understand content types
    Given I am looking to create/edit content in the CMS
     When I view the list of content types
     Then I will see a description for each content type
       And be able to understand the purpose of each content type

  Scenario: Add content
    Given I am looking to create new content
     When I view the list of content types
     Then I will have the ability to add content from this view

  Scenario: View content
    Given I am looking to see all the content for a content type
     When I view the list of content types
     Then I will have the ability to view a list of all the content from a specific content type
```

---

**Content type list context:**
- [ ] Understand content types
- [ ] Add content
- [ ] View content

---

<img width="1233" alt="screen shot 2016-08-11 at 2 21 39 pm" src="https://cloud.githubusercontent.com/assets/3981381/17601692/0441883e-5fcf-11e6-9e20-ef4bfc139430.png">

http://watson-cms.stage1.mybluemix.net/content

**Comment by ineedsubstance** [comment]
🎱 
@joshkimmell @poofichu @mkiang3051 @scottnath - Had a little trouble writing the scenarios for this one, but here you go. Ready for review.

**Comment by mkiang3051** [comment]
@ineedsubstance 
When you say add or view content with 1 click, does that mean the ability to add something prior to clicking into a content type? (e.g., like having buttons to create or view on the screenshot from the CMS you provided above)

Also, are we deciding to show all content types for all users? Or are you putting it in here, in case we decide to go that way? (I think this may also be a bit related to user roles and access that I need to create stories for.)

**Comment by ineedsubstance** [comment]
@mkiang3051 - Yes! Users should be able to perform these actions from the content type list without having to click into it.

I think it would be useful to show all content types for all users. My thought is if we don't display them, then a user wouldn't know what content they don't have access to or to who/how to ask. I think this is still up for debate and needs to be validated.

**Comment by joshkimmell** [comment]
@ineedsubstance will break this into 2 stories. 
- presentation of content types (this)
- more actions to take

**Comment by ineedsubstance** [comment]
Split this up into 2 stories. This story is not a blocker for #444

**Comment by mkiang3051** [comment]
@ineedsubstance 
I have a question about `view content` scenario for the story. Are we talking about the ability to expand a content type on this initial Content Type landing screen and view some of the content in a section without having to click into it? 
Or are you more referencing the view of a certain type of content a user would see upon clicking into a Content Type?

**Comment by mkiang3051** [comment]
@ineedsubstance @joshkimmell @scottnath @poofichu 

Started some quick card designs in mobile for displaying content types. There are 3 main versions so far, with small changes in the way the buttons/links are displayed.
If you could let me know your thoughts and perhaps which of these you like best, that would be very helpful!

These are totally not final, but I wanted some input earlier to help me shape my designs.

Thanks guys!

![mobile card 1](https://cloud.githubusercontent.com/assets/5656022/20287019/82a50344-aa8f-11e6-863d-5a4dd0f463fe.png)

**Comment by mkiang3051** [comment]
Mocks in mobile for very basic actions (seeing content types + their descriptions, adding new content types, and viewing the content under each content type).

V1 has a physical link / button on each `content type` card to `add` new content or to `view` all the content associated with that content type.

V2 has a global `add` button that lets you select the type of content you'd like to add from a menu (instead of having a specific `add` button on each `content type` card)

---

### V1
![mobile v1 1](https://cloud.githubusercontent.com/assets/5656022/20368669/a532d6fc-ac1a-11e6-9776-bb36bcf59b5a.png)

---

### V2
![mobile v2 1](https://cloud.githubusercontent.com/assets/5656022/20368688/b6581f3c-ac1a-11e6-9af9-7c2bc0459952.png)

![mobile v2 1 - universal add with add menu copy](https://cloud.githubusercontent.com/assets/5656022/20368687/b6556b34-ac1a-11e6-82a5-3dfcad1190ba.png)

**Comment by ineedsubstance** [comment]
I think v1 is the better way to go so we are not separating the actions from the content type cards.

**Comment by mkiang3051** [comment]
@ineedsubstance It would definitely make it easier on us not having to create a new menu for a global add. 🙃 I thought of having a global add at the top of the page so that users who come to this page can immediately click on the `add new` button and select a content type to add, instead of scrolling down to find the card of the content type they want, then clicking on a button on that card to add it. It's not that big a deal on desktop since more cards will display, but I was just thinking about on mobile. 

I'll run with the no global `add` idea though and iterate more on card design.

@joshkimmell @poofichu @scottnath Any thoughts?

**Comment by ineedsubstance** [comment]
@mkiang3051 - I think that could be an _additon_ in the future that we explore. I don't think it should be in place of having those actions on the actual cards.

**Comment by mkiang3051** [comment]
@ineedsubstance Yea - that works.

**Comment by mkiang3051** [comment]
Preference for list vs. grid on mobile? See mocks below. (This is with the assumption that the presentation on desktop would be a grid bc of the cards)

NOTE: Don't pay attention to the buttons/information present on these two mocks regarding actions on the cards b/c I know they differ (V1 has two actions, `add` and `view content` while V2 only has a button for `add`. I will post again about card formatting after this post. 

### V1 - List
![mobile v1 1](https://cloud.githubusercontent.com/assets/5656022/20408688/28ab4a52-acdc-11e6-9712-b3a154e5379e.png)

### V2 - Grid
![mobile v3 1](https://cloud.githubusercontent.com/assets/5656022/20408708/342881ce-acdc-11e6-8247-cae1fd4559e8.png)

**Comment by ineedsubstance** [comment]
I like the single column on mobile (more clear with more tappable area for actions) and then expand that out as the view get's bigger.

**Comment by mkiang3051** [comment]
@ineedsubstance Works for me. When you say expand out, do you mean larger cards in grid format for desktop? And maybe just expanded list form in single column for larger mobile screens?

**Comment by mkiang3051** [comment]
@ineedsubstance @joshkimmell @poofichu @scottnath 
Here are some very simple card layout wires.
Versions 1 and 2 each have 2 iterations that have two links/buttons: one for `viewing the content` and then one for `adding new content`. 

Version 3 has 1 physical `link` or `button` for `adding new content` - while I was thinking the larger card overall would be a clickable link/button to view the content. It has 4 iterations that just show ideas of how the `1 button` can be placed.

Let me know your thoughts on whether we want 1 or 2 buttons, or if there is another way we can display this. My preference would be to have a larger area to click on to be taken to view the content, but I think ultimately either do the job.

![mobile card 2](https://cloud.githubusercontent.com/assets/5656022/20492058/f58ed080-afd8-11e6-8369-97b772a0c97b.png)

**Comment by ineedsubstance** [comment]
@mkiang3051 - Good options. Given our current styling for the CMS, and that the title and description could fluctuate a lot, I would say `v1.2` is the best option. 

Although, for all `v3` options, would the `view` action be the title since the button isn't present?

**Comment by mkiang3051** [comment]
@ineedsubstance Suhweet. And yea version two is pretty straightforward and adaptable in case any of the titles and descriptions change. 

I was thinking in all the `v3` options the whole `card` (with the `add new button` as an exception) would be the clickable `view` action. So if a user clicks on anything on that card minus the designated `add` button or section, they would be taken to `view` the available content. 
Would that be feasible? My concern is if that separation would actually work in a real life scenario and that people wouldn't be confused. 

Clicking on the title would be another way it could work without the confusion - but I was trying to think of a way to provide users with a larger `active` area to view items one level deeper, since I know that my first instinct when I see anything that remotely looks like a card is to click on the card itself and not necessarily on specific text or a button to view items one level deeper. I've heard that sentiment around as well. 

Let me know your thoughts on this. Thanks!

**Comment by ineedsubstance** [comment]
Yeah, technically that won't work to have the card as a button with a button on top. The button will actually live inside the card. My opinion is to go with `v1.2`.

**Comment by mkiang3051** [comment]
@ineedsubstance Yea - wishful thinking haha. A button within a button within a button! Yea, `v1.2` is probably easiest to design/implement. Let's go with that! 

Did you want me to try to visually mock up v1.2 in desktop/larger format and/or with some visual styling?

**Comment by ineedsubstance** [comment]
@mkiang3051 - Let's take this to code! We can work together to code this out and take a look at the styling that already exists and adjust from there.

**Comment by mkiang3051** [comment]
@ineedsubstance 
Sounds good! I may or may not be in the office tomorrow - but I can put something on the calendar for next week?

**Comment by ineedsubstance** [comment]
That sounds good to me

**Comment by ineedsubstance** [comment]
@poofichu @joshkimmell - Looking for some opinions here. We have 2 main actions on content types, first is to `add content` and the second is to `view content`. @mkiang3051 and I both think simplifying the button text to `add` and `view` still works for clarity and simplification. What do you guys think? Also, @poofichu, do we need a `secondary` style button here maybe? Maybe just a button with an outline and no color background? Just wondering if that might help distinguish the buttons better.

<img width="623" alt="screen shot 2016-11-28 at 11 09 07 am" src="https://cloud.githubusercontent.com/assets/3981381/20678637/16404ee2-b55d-11e6-83bd-8938f946b7e4.png">

<img width="380" alt="screen shot 2016-11-28 at 11 09 35 am" src="https://cloud.githubusercontent.com/assets/3981381/20678641/199509b6-b55d-11e6-8c02-70bbbd9756dd.png">

**Comment by poofichu** [comment]
The one reason I can see to leave the word "content" is for accessibility reasons.

Otherwise, outlined dark teal button is something I'll need to see to say yay or nay to.

**Comment by ineedsubstance** [comment]
@poofichu - Hmm... didn't think that using `Add` only would be an accessibility issue since it is on the `content` page in the context of a `content type` but you might be right. Is that something testable?

Also, quick mockups of a secondary style button. If you have any suggestions, let me know. I was just thinking we might need something like that for instances where we have 2 buttons next to each other that we want to add some visual hierarchy too.

<img width="627" alt="screen shot 2016-11-28 at 2 19 09 pm" src="https://cloud.githubusercontent.com/assets/3981381/20684471/b03383a8-b575-11e6-9e66-5141515a5635.png">

**Comment by poofichu** [comment]
To be honest, when I'm looking at the 2 different styles, I'm wondering if it really needs it?  This one is still my favorite option:

![image](https://cloud.githubusercontent.com/assets/6757613/20684636/736a3042-b576-11e6-99c9-d10c0609f3af.png)

**Comment by ineedsubstance** [comment]
Cool. That is the one that Miranda and I preferred as well.

**Comment by mkiang3051** [comment]
Yar har! (Triple agreement - oh yea!)
